### ISSUE TITLE
Thanks and a few thoughts

### ISSUE THREAD

**Issue by wrwetzel** [s-yadav/iv-viewer#14] opened 2016-12-16 18:46 UTC
Sudhanshu,

Thanks so much for developing the image viewer. I had evaluated quite a few earlier this year and found none then that did what I want, were understandable, or were easy to use. I just found yours today and it is perfect in all those respects, well, almost. And so a few thoughts...

A callback when the image is loaded would be helpful so that I can extinguish a busy indicator. I added a call to my code at the end of the function "refreshView()" but would prefer an officially supported callback as an option.

My images vary widely in size. When I set a zoom that is suitable for the largest it is much to large for the smaller ones. Please consider an optional alternate expression of the zoom factor based on pixel ratios instead of percent. For example a pixel zoom factor of 1:1 would be a suitable maximum for my largest and smallest images.

I love the snap view, makes it very easy to pan around the large images. However, I believe that it should be at a fixed position on the screen and not scroll with the image. Even better, the fixed position could be specified in an option.

The horizontal and vertical scroll bars are always visible on the screen, even when not needed. I tried briefly to work around this by placing my image in a division which was slightly smaller than the outside container but that was not effective. I suggest that you only show the scroll bars when zooming, not for the original image view.

You can view my use of ImageViewer on the "Asmt Map" or "PClass Map" tabs at my site:

    https://pogodata.wrwetzel.com

By the time you get to view it I may have combined the tabs into one "Static Maps" or just "Maps" tab as your library makes it possible to work with multiple images. That saves real estate on the tabs bar.

Thanks again,
Bill Wetzel

**Comment by wrwetzel** [comment] 2016-12-16 18:59
Oops, I may have been a bit hasty in my comment about the scroll bar. I just saw in your demo that the bars are not present. Perhaps I can remove mine with css.

**Comment by wrwetzel** [comment] 2016-12-16 23:48
Please disregard all of my comments in my first post about the scroll bars. They are not an issue. A couple of more thoughts...

Your documentation on the html and javascript code is excellent. It worked just fine with minor tweaking. It would be helpful to have similar documentation on the required css. I had to go to the source of your demo page to find that. Once I included it many problems resolved.

Your demo code includes the following:
` wrapper.find('.prev').click(function(){
         curImageIdx--;
        if(curImageIdx < 0) curImageIdx = total;
        showImage();
    });`
I believe the comparison with zero should be "<=", not "<", i.e.:
     `if(curImageIdx <= 0) curImageIdx = total;`

It would be helpful if to have a method that returned the current value for "zoomValue" and "point" that could be used used as arguments to the zoom(zoomValue,point) method. While I can keep track of such data when I change zoom by program I would like to be able to obtain the values when the user zooms so that I can restore those values after changing the image.

That's about all for now
Thanks again for a great library. Very helpful.
My site again, this time as a link.

   [https://pogodata.wrwetzel.com/](url)

**Comment by wrwetzel** [comment] 2016-12-16 23:59
One more thing I just saw. The snap view window sometimes disappears when dragging the slider on it. I can't reproduce it consistently but I did see it several times.

By the way, tested the library on recent versions of Internet Explorer, Chrome, Opera, and Firefox and it appears to work fine on all of them.

**Comment by s-yadav** [comment] 2016-12-20 09:27
@wrwetzel 

Thanks for your input, and thanks for testing it on all browsers. 

Here are my thoughts

``_A callback when the image is loaded would be helpful so that I can extinguish a busy indicator. I added a call to my code at the end of the function "refreshView()" but would prefer an officially supported callback as an option._``

ImageViewer support two type of images a low res image and a high res image, so the normal flow is load the low res first and then load the higher res image. So in case if you already loaded low res images in your page on click of which you want to show image viewer, you can show something to user (the same image) while high res image is loading.  So in such cases you will not be needing a loading indicator.
But in case you have not loaded that image already, indicator makes sense. Will add the loading callback, or will add acclass on wrapper element called loading, using which you can show loading icon.

`_My images vary widely in size. When I set a zoom that is suitable for the largest it is much to large for the smaller ones. Please consider an optional alternate expression of the zoom factor based on pixel ratios instead of percent. For example a pixel zoom factor of 1:1 would be a suitable maximum for my largest and smallest images._`

I am not sure if I understood this. Right now zoomValue is relative to your image size.

``_Your documentation on the html and javascript code is excellent. It worked just fine with minor tweaking. It would be helpful to have similar documentation on the required css. I had to go to the source of your demo page to find that. Once I included it many problems resolved._``

Will add that.  I will also fix the js snippet

`_It would be helpful if to have a method that returned the current value for "zoomValue" and "point" that could be used used as arguments to the zoom(zoomValue,point) method. While I can keep track of such data when I change zoom by program I would like to be able to obtain the values when the user zooms so that I can restore those values after changing the image._`

point is the point in container not the image, I will see what can be done with this.

`_The snap view window sometimes disappears when dragging the slider on it. I can't reproduce it consistently but I did see it several times._`

The snap view autohides if you are not having interaction with the viewer. but as soon you move the mouse it should show back. Is anything different happening here ?

**Comment by wrwetzel** [comment] 2016-12-21 17:35
Sudhanshu,

Thanks for getting back and for your comments.

Callback when load complete - I am now using both low and high resolution images. That works great and gives the user an indication of progress during loading. However, I would still like to use a busy indicator for consistency with the rest of my site.

Zoom factor - Let me try to clarify this. I would like be able to specify to zoom to a factor tsuch hat each pixel in the image corresponds to one pixel on the screen, that is, 1:1, no matter what the size of the image is. I believe that will be sufficient and I can zoom by percentages up and down from there and down to the 100% factor. For example, if the image is 1000px wide and the view window is 200 px wide, then the "zoom 1:1" would acually zoom in by 500%. If I load a new image  that is 2000px wide, then the same "zoom 1:1" would now actually zoom in by 1000%. Conversely, if I load an image that is 200px wide then "zoom 1:1" would do nothing. I attempted to accomplish this myself by computing a zoom factor based on window size and image size but I didn't have access to the image size and didn't want to read the entire image to get it. Some of the images are in the several tens of megabytes and adding an extra read would slow things down. As an alternative to implementing a "zoom 1:1" method I could do the arithmetic myself if you could provide a method to get the actual image size. That may be the easiest and quickest approach. The downside of this is that I won't have the image size until after the call to viewer.load() but I need it for the call to ImageViewer() to specify a maximum zoom. It would be very helpful to have an alternate expression of maximum zoom based on pixel ratios instead of percent. I can limit the zoom when a user clicks a zoom button the I provide but I can't limit it when the user is zooming with the slider on the snap window. For example, a maxZoomPixel of 1.0 would permit zooming to 1:1 no matter what the image size or viewport. A maxZoomPixel of 2.0 would permit zooming to twice that and so on with fractional maxZoomPixel values restricting zooming to less than 1:1.

Access to zoomValue and point - let me explain the need for this. My web site shows maps of towns colored based on various parameters - property class and assessed value right now - so called "thematic maps". If the user is viewing the property class map and then switches to the asses value map it would be best to preserve the exact viewport such that all parcels are at the exact same location on the screen. That would enable a comparison  of the displayed parameters.

Snapview indeed does autohide but I was seeing it autohide while I was moving the slider in the snapview window. I'm unable to reproduce the situation now but I'm confident I saw it several times during testing. I'll keep an eye on it and let you know if it happens again.

I think that about covers everything we talked about.
Thanks again for getting back. You can view your library in action on the "Thematic Maps" tab at: https://pogodata.org.

Bill

**Comment by s-yadav** [comment] 2019-05-17 20:48
Closing this in favor of v2. And also the issue has got very old.

**Closed as completed by s-yadav** 2019-05-17 20:48 UTC
